###
#Shows all users in db
###
GET http://localhost:8080/api/user

###
#Creates User
###
POST http://localhost:8080/api/user/create HTTP/1.1
content-type: application/json

{
    "login": "admisness",
    "password": "ziomek",
    "email": "ziome12sk@gmail.com",
    "name": "ziomowit",
    "surname": "ziomkowski"
}

###
#Login for User
###
POST http://localhost:8080/api/user/login HTTP/1.1
content-type: application/json

{
    "login": "admisness",
    "password": "ziomek"
}