###
#Shows all users in db
###
GET http://localhost:8080/api/user

###
#Creates User
###
POST http://localhost:8080/api/user/create HTTP/1.1
content-type: application/json

{
    "login": "test",
    "password": "test",
    "email": "test@gmail.com",
    "name": "milek",
    "surname": "wilk"
}


###
#Login for User with JWT response
###
POST http://localhost:8080/api/user/auth HTTP/1.1
content-type: application/json

{
    "emailorlogin": "te1st",
    "password": "test"
}

###
#Gets DOM selector content from html file
###
POST http://localhost:8080/api/sites/htmlcontent HTTP/1.1
content-type: application/json

{
    "dom": "#wrapper",
    "id": 13 
}

###
#Updates DOM selector content within html file
###
POST http://localhost:8080/api/sites/htmlcontent/update HTTP/1.1
content-type: application/json

{
    "dom": "#footer",
    "content": "Zmieni2ony fo2oter :)",
    "file": "index.html"
}

###
#Deletes html file to public/sites then from db
###
GET http://localhost:8080/api/sites/12  /delete HTTP/1.1
content-type: application/json

